name: test-status-check-functions

on:
  workflow_dispatch:
  pull_request:

jobs:
#   success-job:
#     runs-on: ubuntu-latest
#     steps:
#         - name: success
#           run: exit 0
#         - name: if success execute
#           if: success()
#           run: echo 'in success'

  failure-job:
    runs-on: ubuntu-latest
    steps:
        - name: failure
          run: exit 1
        - name: success
          run: exit 0
        - name: if failure execute
          if: failure()
          run: echo 'in failure'